services:
  product-db:
    image: mongo:7.0
    ports:
      - "27018:27017"
  inventory-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_PASSWORD=123"
  order-db:
    image: postgres:16.1
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_PASSWORD=123"
  rabbit-mq:
    image: rabbitmq:3.13.0-rc.2-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_PASS=user"
      - "RABBITMQ_DEFAULT_USER=user"